### PR TITLE
17 make nightlife rabbet capture logs in a text file

### PR DESCRIPTION
**Pull request by andySigler**
This branch removes the console logging from the nightlife-rabbit WAMP router, and instead sends all router logs to `router_logfile.txt` inside the `otone_data` folder.

There are to changes to `app/package.json`'s dependencies:
1. nightlife-rabbit dependency points to an opentrons fork of the project, allowing custom loggers
2. the nodejs logger winston is added to dependencies

### CODE REVIEW

**Comment by andySigler** [comment]
@SimplyAhmazing @levthedev once this PR is merged, the electron app won't be filled with those nightlife-rabbit logs any more :)

**Comment by levthedev** [comment]
I'm OK with this as long as the nightlife fork is necessary. But it looks like CLogger supports logging to a file - the only feature I can see that we need in Winston that's not in CLogger is the max file length thing. Have you looked into a way to do that with CLogger?

**Comment by andySigler** [comment]
@lev I've looked into CLogger for a maxfile parameter and could not find one.

The fork of nightlife-rabbit is necessary, because the router's default logger was not able to be overwritten before, [as brought up in this issue](https://github.com/christian-raedel/nightlife-rabbit/issues/6)

**Comment by levthedev** [comment]
ok then, LGTM 💯

**Pull request merged**
