### PR TITLE
remove links to external websites

### PR DESCRIPTION
**Pull request by levthedev**
these open new electron windows, which is weird for users because then they realize our app is just a glorified browser, not to mention the fact that we don't want to link to external websites (though maybe we can have them launch the default browser? not sure if there's an non OS specific way to do that)

### CODE REVIEW

**Comment by nwags** [comment]
Looks good to me ;)

**Comment by andySigler** [comment]
Yup this is good. One thing is that they're still `<a>` tags, so the cursor turns into a pointer when hovering over. There could be a new CSS class that removes the pointer from links, something like:

``` css
dead_link:hover { 
    cursor:default;
}
```

At one point I tried changing them to `<span>` elements to fix this, but they displayed differently and I didn't want to play around with CSS too much.

**Comment by levthedev** [comment]
@andySigler I disagree - on my computer my mouse does not turn into a pointer, even without another CSS class. Have you seen this behavior on your computer? I'm pretty sure that <a> tags without an href attribute maintain a normal pointer, like a <span>.

**Comment by andySigler** [comment]
OK cool looks good 👍

**Pull request merged**
